### ISSUE TITLE
No frequencies for capitalized words (German)

### ISSUE THREAD

**Issue by emanuelps2708** [StefanVukovic99/leipzig-to-yomitan#3]
Hi, thanks for making these frequency lists, they're great.
it appears that the frequencies for German are not case sensitive, which causes a lot of entries not having any value.
![Screenshot from 2024-08-08 06-53-02](https://github.com/user-attachments/assets/59a44bdc-9e2c-4fcf-bb60-a8e276c94075)
![Screenshot from 2024-08-08 06-50-35](https://github.com/user-attachments/assets/7ed27962-0702-48e1-a62b-aab04fa23863)

**Comment by StefanVukovic99** [comment]
Yeah, I noticed that too. I don't know if there are any other languages that use capitalization in the same way, but I fixed it for german in 9b89c19b67175a98c0448f208b15953fcf9982dc so they should work in the next release.
